
package resource;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthServiceResourceImplService", targetNamespace = "http://www.example.org/auth/", wsdlLocation = "file:/C:/Users/Fadi/Desktop/KTH/Y1P3/Programming Web-Services/Exercises/2016/Homework2/src/main/resources/flightReservation-doc.wsdl")
public class AuthServiceResourceImplService
    extends Service
{

    private final static URL AUTHSERVICERESOURCEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHSERVICERESOURCEIMPLSERVICE_EXCEPTION;
    private final static QName AUTHSERVICERESOURCEIMPLSERVICE_QNAME = new QName("http://www.example.org/auth/", "AuthServiceResourceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Fadi/Desktop/KTH/Y1P3/Programming Web-Services/Exercises/2016/Homework2/src/main/resources/flightReservation-doc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHSERVICERESOURCEIMPLSERVICE_WSDL_LOCATION = url;
        AUTHSERVICERESOURCEIMPLSERVICE_EXCEPTION = e;
    }

    public AuthServiceResourceImplService() {
        super(__getWsdlLocation(), AUTHSERVICERESOURCEIMPLSERVICE_QNAME);
    }

    public AuthServiceResourceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHSERVICERESOURCEIMPLSERVICE_QNAME, features);
    }

    public AuthServiceResourceImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTHSERVICERESOURCEIMPLSERVICE_QNAME);
    }

    public AuthServiceResourceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHSERVICERESOURCEIMPLSERVICE_QNAME, features);
    }

    public AuthServiceResourceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthServiceResourceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthServiceResource
     */
    @WebEndpoint(name = "AuthServiceResourceImplPort")
    public AuthServiceResource getAuthServiceResourceImplPort() {
        return super.getPort(new QName("http://www.example.org/auth/", "AuthServiceResourceImplPort"), AuthServiceResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthServiceResource
     */
    @WebEndpoint(name = "AuthServiceResourceImplPort")
    public AuthServiceResource getAuthServiceResourceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/auth/", "AuthServiceResourceImplPort"), AuthServiceResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHSERVICERESOURCEIMPLSERVICE_EXCEPTION!= null) {
            throw AUTHSERVICERESOURCEIMPLSERVICE_EXCEPTION;
        }
        return AUTHSERVICERESOURCEIMPLSERVICE_WSDL_LOCATION;
    }

}
