//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 07:28:56 PM CET 
//


package com.company;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="userdata"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="personnummer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="personalLetter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="employmentRecord"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="employment"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="degrees"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="degree"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="uniName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="GPA" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userdata",
    "employmentRecord",
    "degrees"
})
@XmlRootElement(name = "applicantProfile")
public class ApplicantProfile {

    @XmlElement(required = true)
    protected ApplicantProfile.Userdata userdata;
    @XmlElement(required = true)
    protected ApplicantProfile.EmploymentRecord employmentRecord;
    @XmlElement(required = true)
    protected ApplicantProfile.Degrees degrees;

    /**
     * Gets the value of the userdata property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantProfile.Userdata }
     *     
     */
    public ApplicantProfile.Userdata getUserdata() {
        return userdata;
    }

    /**
     * Sets the value of the userdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantProfile.Userdata }
     *     
     */
    public void setUserdata(ApplicantProfile.Userdata value) {
        this.userdata = value;
    }

    /**
     * Gets the value of the employmentRecord property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantProfile.EmploymentRecord }
     *     
     */
    public ApplicantProfile.EmploymentRecord getEmploymentRecord() {
        return employmentRecord;
    }

    /**
     * Sets the value of the employmentRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantProfile.EmploymentRecord }
     *     
     */
    public void setEmploymentRecord(ApplicantProfile.EmploymentRecord value) {
        this.employmentRecord = value;
    }

    /**
     * Gets the value of the degrees property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantProfile.Degrees }
     *     
     */
    public ApplicantProfile.Degrees getDegrees() {
        return degrees;
    }

    /**
     * Sets the value of the degrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantProfile.Degrees }
     *     
     */
    public void setDegrees(ApplicantProfile.Degrees value) {
        this.degrees = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="degree"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="uniName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="GPA" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "degree"
    })
    public static class Degrees {

        @XmlElement(required = true)
        protected ApplicantProfile.Degrees.Degree degree;

        /**
         * Gets the value of the degree property.
         * 
         * @return
         *     possible object is
         *     {@link ApplicantProfile.Degrees.Degree }
         *     
         */
        public ApplicantProfile.Degrees.Degree getDegree() {
            return degree;
        }

        /**
         * Sets the value of the degree property.
         * 
         * @param value
         *     allowed object is
         *     {@link ApplicantProfile.Degrees.Degree }
         *     
         */
        public void setDegree(ApplicantProfile.Degrees.Degree value) {
            this.degree = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="uniName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="GPA" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "uniName",
            "type",
            "gpa"
        })
        public static class Degree {

            @XmlElement(required = true)
            protected String uniName;
            @XmlElement(required = true)
            protected String type;
            @XmlElement(name = "GPA")
            protected float gpa;

            /**
             * Gets the value of the uniName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUniName() {
                return uniName;
            }

            /**
             * Sets the value of the uniName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUniName(String value) {
                this.uniName = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the gpa property.
             * 
             */
            public float getGPA() {
                return gpa;
            }

            /**
             * Sets the value of the gpa property.
             * 
             */
            public void setGPA(float value) {
                this.gpa = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="employment"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employment"
    })
    public static class EmploymentRecord {

        @XmlElement(required = true)
        protected ApplicantProfile.EmploymentRecord.Employment employment;

        /**
         * Gets the value of the employment property.
         * 
         * @return
         *     possible object is
         *     {@link ApplicantProfile.EmploymentRecord.Employment }
         *     
         */
        public ApplicantProfile.EmploymentRecord.Employment getEmployment() {
            return employment;
        }

        /**
         * Sets the value of the employment property.
         * 
         * @param value
         *     allowed object is
         *     {@link ApplicantProfile.EmploymentRecord.Employment }
         *     
         */
        public void setEmployment(ApplicantProfile.EmploymentRecord.Employment value) {
            this.employment = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "code",
            "from",
            "to"
        })
        public static class Employment {

            @XmlElement(required = true)
            protected String code;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar from;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar to;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the from property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFrom(XMLGregorianCalendar value) {
                this.from = value;
            }

            /**
             * Gets the value of the to property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTo(XMLGregorianCalendar value) {
                this.to = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="personnummer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="personalLetter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fullname",
        "personnummer",
        "personalLetter"
    })
    public static class Userdata {

        @XmlElement(required = true)
        protected String fullname;
        @XmlElement(required = true)
        protected String personnummer;
        @XmlElement(required = true)
        protected String personalLetter;

        /**
         * Gets the value of the fullname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullname() {
            return fullname;
        }

        /**
         * Sets the value of the fullname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullname(String value) {
            this.fullname = value;
        }

        /**
         * Gets the value of the personnummer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonnummer() {
            return personnummer;
        }

        /**
         * Sets the value of the personnummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonnummer(String value) {
            this.personnummer = value;
        }

        /**
         * Gets the value of the personalLetter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonalLetter() {
            return personalLetter;
        }

        /**
         * Sets the value of the personalLetter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonalLetter(String value) {
            this.personalLetter = value;
        }

    }

}
