//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 07:28:56 PM CET 
//


package com.company;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.company package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.company
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CompanyInfo }
     * 
     */
    public CompanyInfo createCompanyInfo() {
        return new CompanyInfo();
    }

    /**
     * Create an instance of {@link com.company.EmploymentRecord }
     * 
     */
    public com.company.EmploymentRecord createEmploymentRecord() {
        return new com.company.EmploymentRecord();
    }

    /**
     * Create an instance of {@link Transcript }
     * 
     */
    public Transcript createTranscript() {
        return new Transcript();
    }

    /**
     * Create an instance of {@link ApplicantProfile }
     * 
     */
    public ApplicantProfile createApplicantProfile() {
        return new ApplicantProfile();
    }

    /**
     * Create an instance of {@link ApplicantProfile.Degrees }
     * 
     */
    public ApplicantProfile.Degrees createApplicantProfileDegrees() {
        return new ApplicantProfile.Degrees();
    }

    /**
     * Create an instance of {@link ApplicantProfile.EmploymentRecord }
     * 
     */
    public ApplicantProfile.EmploymentRecord createApplicantProfileEmploymentRecord() {
        return new ApplicantProfile.EmploymentRecord();
    }

    /**
     * Create an instance of {@link Transcript.Courses }
     * 
     */
    public Transcript.Courses createTranscriptCourses() {
        return new Transcript.Courses();
    }

    /**
     * Create an instance of {@link Transcript.Degrees }
     * 
     */
    public Transcript.Degrees createTranscriptDegrees() {
        return new Transcript.Degrees();
    }

    /**
     * Create an instance of {@link CompanyInfo.Company }
     * 
     */
    public CompanyInfo.Company createCompanyInfoCompany() {
        return new CompanyInfo.Company();
    }

    /**
     * Create an instance of {@link com.company.EmploymentRecord.Employment }
     * 
     */
    public com.company.EmploymentRecord.Employment createEmploymentRecordEmployment() {
        return new com.company.EmploymentRecord.Employment();
    }

    /**
     * Create an instance of {@link ShortCV }
     * 
     */
    public ShortCV createShortCV() {
        return new ShortCV();
    }

    /**
     * Create an instance of {@link ApplicantProfile.Userdata }
     * 
     */
    public ApplicantProfile.Userdata createApplicantProfileUserdata() {
        return new ApplicantProfile.Userdata();
    }

    /**
     * Create an instance of {@link ApplicantProfile.Degrees.Degree }
     * 
     */
    public ApplicantProfile.Degrees.Degree createApplicantProfileDegreesDegree() {
        return new ApplicantProfile.Degrees.Degree();
    }

    /**
     * Create an instance of {@link ApplicantProfile.EmploymentRecord.Employment }
     * 
     */
    public ApplicantProfile.EmploymentRecord.Employment createApplicantProfileEmploymentRecordEmployment() {
        return new ApplicantProfile.EmploymentRecord.Employment();
    }

    /**
     * Create an instance of {@link Transcript.Courses.Course }
     * 
     */
    public Transcript.Courses.Course createTranscriptCoursesCourse() {
        return new Transcript.Courses.Course();
    }

    /**
     * Create an instance of {@link Transcript.Degrees.Degree }
     * 
     */
    public Transcript.Degrees.Degree createTranscriptDegreesDegree() {
        return new Transcript.Degrees.Degree();
    }

}
