//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 07:28:56 PM CET 
//


package com.company;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="personnummer"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="\d{6}-\d{4}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="briefBio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="personalLetter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fullname",
    "personnummer",
    "briefBio",
    "personalLetter"
})
@XmlRootElement(name = "shortCV")
public class ShortCV {

    @XmlElement(required = true)
    protected String fullname;
    @XmlElement(required = true)
    protected String personnummer;
    @XmlElement(required = true)
    protected String briefBio;
    @XmlElement(required = true)
    protected String personalLetter;

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullname(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the personnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonnummer() {
        return personnummer;
    }

    /**
     * Sets the value of the personnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonnummer(String value) {
        this.personnummer = value;
    }

    /**
     * Gets the value of the briefBio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBriefBio() {
        return briefBio;
    }

    /**
     * Sets the value of the briefBio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBriefBio(String value) {
        this.briefBio = value;
    }

    /**
     * Gets the value of the personalLetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalLetter() {
        return personalLetter;
    }

    /**
     * Sets the value of the personalLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalLetter(String value) {
        this.personalLetter = value;
    }

}
