
package resource;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthServiceResource", targetNamespace = "http://www.example.org/auth/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthServiceResource {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "token", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.example.org/auth/", className = "org.example.auth.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.example.org/auth/", className = "org.example.auth.LoginResponse")
    public String login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
