
package resource;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ItineraryServiceResourceImplService", targetNamespace = "http://resource/", wsdlLocation = "http://localhost:8080/soap/itinerary?WSDL")
public class ItineraryServiceResourceImplService
    extends Service
{

    private final static URL ITINERARYSERVICERESOURCEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITINERARYSERVICERESOURCEIMPLSERVICE_EXCEPTION;
    private final static QName ITINERARYSERVICERESOURCEIMPLSERVICE_QNAME = new QName("http://resource/", "ItineraryServiceResourceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap/itinerary?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITINERARYSERVICERESOURCEIMPLSERVICE_WSDL_LOCATION = url;
        ITINERARYSERVICERESOURCEIMPLSERVICE_EXCEPTION = e;
    }

    public ItineraryServiceResourceImplService() {
        super(__getWsdlLocation(), ITINERARYSERVICERESOURCEIMPLSERVICE_QNAME);
    }

    public ItineraryServiceResourceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITINERARYSERVICERESOURCEIMPLSERVICE_QNAME, features);
    }

    public ItineraryServiceResourceImplService(URL wsdlLocation) {
        super(wsdlLocation, ITINERARYSERVICERESOURCEIMPLSERVICE_QNAME);
    }

    public ItineraryServiceResourceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITINERARYSERVICERESOURCEIMPLSERVICE_QNAME, features);
    }

    public ItineraryServiceResourceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItineraryServiceResourceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItineraryServiceResource
     */
    @WebEndpoint(name = "ItineraryServiceResourceImplPort")
    public ItineraryServiceResource getItineraryServiceResourceImplPort() {
        return super.getPort(new QName("http://resource/", "ItineraryServiceResourceImplPort"), ItineraryServiceResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItineraryServiceResource
     */
    @WebEndpoint(name = "ItineraryServiceResourceImplPort")
    public ItineraryServiceResource getItineraryServiceResourceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resource/", "ItineraryServiceResourceImplPort"), ItineraryServiceResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITINERARYSERVICERESOURCEIMPLSERVICE_EXCEPTION!= null) {
            throw ITINERARYSERVICERESOURCEIMPLSERVICE_EXCEPTION;
        }
        return ITINERARYSERVICERESOURCEIMPLSERVICE_WSDL_LOCATION;
    }

}
